
# tap repositories and their packages

tap homebrew/core
brew ansible
brew aom
brew autoconf
brew awscli
brew bdw-gc
brew brotli
brew ca-certificates
brew cairo
brew cask
brew cjson
brew cmocka
brew coreutils
brew curl
brew dav1d
brew direnv
brew docutils
brew emacs
brew ffmpeg
brew findutils
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew gdbm
brew gettext
brew giflib
brew git
brew git-ftp
brew git-lfs
brew git-secrets
brew glib
brew gmp
brew gnu-sed
brew gnutls
brew goaccess
brew gobject-introspection
brew graphite2
brew grep
brew guile
brew handbrake
brew harfbuzz
brew highway
brew htmlq
brew icu4c
brew imath
brew jansson
brew jpeg
brew jpeg-turbo
brew jpeg-xl
brew jq
brew lame
brew leptonica
brew lftp
brew libarchive
brew libass
brew libb2
brew libbluray
brew libcbor
brew libevent
brew libffi
brew libfido2
brew libidn2
brew libmaxminddb
brew libnghttp2
brew libogg
brew libpng
brew libpthread-stubs
brew librist
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunibreak
brew libunistring
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew little-cms2
brew lz4
brew lzo
brew m4
brew mas
brew mbedtls
brew mpdecimal
brew mpg123
brew mysql-client
brew nettle
brew nodebrew
brew oniguruma
brew opencore-amr
brew openexr
brew openjpeg
brew openldap
brew openssl@1.1
brew opus
brew p11-kit
brew pango
brew pcre
brew pcre2
brew pixman
brew pkg-config
brew pyenv
brew pyenv-virtualenv
brew python@3.10
brew python@3.11
brew python@3.9
brew pyyaml
brew rav1e
brew readline
brew rtmpdump
brew rubberband
brew sdl2
brew six
brew snappy
brew speex
brew sqlite
brew srt
brew tcl-tk
brew terraformer
brew tesseract
brew tfenv
brew theora
brew tokyo-cabinet
brew unar
brew unbound
brew visitors
brew webp
brew wget
brew x264
brew x265
brew xorgproto
brew xvid
brew xz
brew zeromq
brew zimg
brew zlib
brew zstd

tap homebrew/cask-drivers
cask logitech-options
cask ricoh-theta

tap homebrew/cask-fonts
cask font-fontawesome
cask font-noto-sans-cjk
cask font-noto-serif-cjk

tap homebrew/cask-versions
cask safari-technology-preview

tap homebrew/cask
cask adobe-creative-cloud
cask alfred
cask brave-browser
cask chrome-remote-desktop-host
cask coteditor
cask day-o
cask dbeaver-community
cask dropbox
cask figma
cask firefox
cask fliqlo
cask geekbench
cask google-chrome
cask handbrake
cask jdownloader
cask karabiner-elements
cask keepassx
cask libreoffice
cask microsoft-remote-desktop
cask scroll-reverser
cask sketch
cask sqlectron
cask vagrant
cask virtualbox
cask visual-studio-code
cask vlc
cask zoom

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 549083868   Display Menu  (2.2.4)
appstore 1496833156  Playgrounds   (4.1)
appstore 1429033973  RunCat        (9.7)
appstore 803453959   Slack         (4.29.149)
appstore 497799835   Xcode         (14.0.1)
